### ISSUE TITLE
keeps giving me this error when i install the req

### ISSUE THREAD

**Issue by envy3434** [RojanGamingYT/Discord-Username-Sniper#11]
ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os

**Comment by o1j** [comment]
delete this modules from req txt file

os
sys
time
threading

**Comment by RojanGamingYT** [comment]
I hope the Issue has been solved, If not reply here within 12 hours otherwise this issue will be closed.

**Comment by bofahad11** [comment]
Thanks, is it passing captacha?
