### ISSUE TITLE
Every name is appearing as avaliable, although it isn't

### ISSUE THREAD

**Issue by wattsoner** [RojanGamingYT/Discord-Username-Sniper#16]
Describe the bug
Every name I've put into names.txt has said it's avaliable, although it isn't

To Reproduce
go to names.txt and enter dictionary words
save, go to checker and press option to check
enter token
allow program to run
see error.

Expected behavior
these names shouldn't be avaliable (they aren't but it says they are)

I'm on windows

**Comment by RojanGamingYT** [comment]
Hey, This bug is caused because the Token you're using doesn't have the new username access. If that's not the case and it has username access do reply I'll check for it to get fixed

**Comment by 97249122** [comment]
I do have the new username access, it doesn't work unfortunately :c

**Comment by RojanGamingYT** [comment]
I will look for its fix

**Comment by 97249122** [comment]
> I will look for its fix

Thanks so much! This project is super cool but I just couldn't use it, props for the response though :)

**Comment by RojanGamingYT** [comment]
This may take longer than expected but have some patience I will get it fixed with keeping in mind the new system to bypass it without any further error

**Comment by 97249122** [comment]
> This may take longer than expected but have some patience I will get it fixed with keeping in mind the new system to bypass it without any further error

thanks so much, I bet its super annoying to find a bypass for it

**Comment by 97249122** [comment]
hey, have you managed to find a fix for this?

**Comment by RojanGamingYT** [comment]
I haven't found a fix yet

**Comment by 97249122** [comment]
found a fix yet?

**Comment by RojanGamingYT** [comment]
There hasn't  been a fix to it yet

**Comment by FR12Gimenez** [comment]
Theres a new endpoint.

**Comment by 97249122** [comment]
can this be fixed?

**Comment by aikooo7** [comment]
Hello @RojanGamingYT do you want help fixing the issue?

**Comment by RojanGamingYT** [comment]
> Hello @RojanGamingYT do you want help fixing the issue?

Yeah sure @aikooo7 , If you're able to fix it try doing it I haven't been able to bypass the API and if it works open a pull request I'll merge your PR

**Comment by 103Starboy** [comment]
hey @RojanGamingYT is it fixed now?

**Comment by RojanGamingYT** [comment]
> hey @RojanGamingYT is it fixed now?

I have discontinued making the changes due to discord's frequent updates to their username system, Since then many users created a working script so I haven't looked at fixing this.

**Comment by 01NoN** [comment]
> > hey @RojanGamingYT is it fixed now?
> 
> I have discontinued making the changes due to discord's frequent updates to their username system, Since then many users created a working script so I haven't looked at fixing this.

is it fixed now?

**Comment by alluding** [comment]
> > > hey @RojanGamingYT is it fixed now?
> > 
> > 
> > I have discontinued making the changes due to discord's frequent updates to their username system, Since then many users created a working script so I haven't looked at fixing this.
> 
> is it fixed now?

The fix is quite easy. As for the checker, we have two possible endpoints that are better than using the pomelo endpoint itself. You can utilize the register username check endpoint, which has fewer rate limits, and when you do get rate-limited, the cooldown is MUCH smaller compared to the pomelo. We also have the suggestion username endpoint, which is a part of the register as well. It's a little different. To figure out if a username is taken or not with this endpoint, you'd have to check the response. If it returns anything BESIDES the given username, that means it's taken. For example, if I give `revenge`, it would return something like `revenge1238` because it's taken. If it wasn't, it would only return `revenge`.
