### ISSUE TITLE
Feature Request :

### ISSUE THREAD

**Issue by Someone3731** [RojanGamingYT/Discord-Username-Sniper#17]
**Is your feature request related to a problem? Please describe.**
Tool block because of capchat

**Describe the solution you'd like**
Auto-add capcha extension in selenium

**Describe alternatives you've considered**
For more realistic traffic `undetected_chromedriver` lib could be used (optional)

**Additional context**
I'm unsure to know if capcha is alway hcapcha or varie

**Comment by RojanGamingYT** [comment]
Unfortunately, I have discontinued working on this repository.
