### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Akash1338** [RojanGamingYT/Discord-Username-Sniper#18]
**Describe the bug**
a huge ass error

**To Reproduce**
1. Go to the sniper's folder
2. Open cmd
3. Execute the sniper, entering the token bla bla

**Expected behavior**
I expected it to try and snipe the username of course lmao

**Screenshots**
![image](https://github.com/RojanGamingYT/Discord-Username-Sniper/assets/125605618/75bea17b-a514-4481-b79a-3778562e0118)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera gx
 - Version 10 22h2

**Comment by RojanGamingYT** [comment]
You must have chrome and chromedriver of 114 version installed on your device for it to work!

**Comment by Akash1338** [comment]
i cant find chrome driver for the latest chrome version 114
