### ISSUE TITLE
Where do I put captcha key at?

### ISSUE THREAD

**Issue by LyThaGawd** [RojanGamingYT/Discord-Username-Sniper#19]
The sniper works, but when I submits the request and a captcha pops up it will close the window

**Comment by LyThaGawd** [comment]
![image](https://github.com/RojanGamingYT/Discord-Username-Sniper/assets/86447045/789dbfdb-85a8-4d1c-b680-853c3ad7311b)

**Comment by RojanGamingYT** [comment]
Hey, The Code isn't working at the moment !
