### ISSUE TITLE
I got issue while using pip install.

### ISSUE THREAD

**Issue by MustafaEsatTemel** [RojanGamingYT/Discord-Username-Sniper#5]
![image](https://github.com/RojanGamingYT/Discord-Username-Sniper/assets/65919257/0ca85ca7-d2e5-4cc0-82b6-56f7ac3cedcb)
Also :
![image](https://github.com/RojanGamingYT/Discord-Username-Sniper/assets/65919257/7848dff5-f59e-417b-a640-78c2af804ad8)

**Comment by RojanGamingYT** [comment]
Do `pip install tls_client` to install the missing package

**Comment by MustafaEsatTemel** [comment]
Yeah it fixed my problem. And i have one more question. Old version of your sniper was better. I want to generate 3 letter or 4 letter username but don't have option for it.

**Comment by RojanGamingYT** [comment]
The old version didn't work so I had it revamp it, next version will focus upon the short letter usernames .

**Comment by RojanGamingYT** [comment]
Since there isn't any further conversation here, I'll close this.
