### ISSUE TITLE
You need to update your app to perform this action.

### ISSUE THREAD

**Issue by NotRexi** [RojanGamingYT/Discord-Username-Sniper#6]
I edited the python file because it didn't work, wouldn't change the user or anything but I fixed it. There's just a slight issue, when I get to the captcha part it says, [-] Failed to change username: {"captcha_key": ["You need to update your app to perform this action."] and all the other nonsense like the sitekey. How am I supposed to update it? Also is there any other way to bypass the captcha? 
(Attached the modified code in a txt)
[UserSniperHelp.txt](https://github.com/RojanGamingYT/Discord-Username-Sniper/files/11763729/UserSniperHelp.txt)

**Comment by RojanGamingYT** [comment]
This might have been patched, They have added a captcha field while getting the username. Captcha bypass is possible but you need a captcha bypass key and the code must be updated for it

**Comment by RojanGamingYT** [comment]
To update your app error you need to look at the `tls_client` and update the client version which is currently at `chrome110` or replace it with another package which can fix that issue and can work with Pomelo of discord and Yes 2captcha can possibly bypass it but there may be a possibility that Hcaptcha which Discord uses which is a little more complex than the Recaptcha and 2captcha may not solve it without any errors and you can possibly use `https://capsolver.com/` for better results and speed.

**Comment by RojanGamingYT** [comment]
The Issue has been  fixed
