### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ST4RTER** [RojanGamingYT/Discord-Username-Sniper#7]
got this error on multiple accounts 
[-] Failed to snipe {"message": "Unauthorized", "code": 40001}
happens after I enter the details

**Comment by RojanGamingYT** [comment]
Your Account doesn't have the username access for it to work

**Comment by RojanGamingYT** [comment]
> got this error on multiple accounts [-] Failed to snipe {"message": "Unauthorized", "code": 40001} happens after I enter the details

**The New Code Update has fixed this issue**
