### ISSUE TITLE
problem with captcha

### ISSUE THREAD

**Issue by bofahad11** [RojanGamingYT/Discord-Username-Sniper#9]
Hey Rojan, first of all Thank you for the effort spent in creating the script

I have problem with 2Captcha, it show an error on cmd
![image](https://github.com/RojanGamingYT/Discord-Username-Sniper/assets/137083498/b5d23697-5ca8-41d0-9aad-118549c704b9)

by the way i have enough balance on 2Captcha

How can i solve it?

**Comment by bofahad11** [comment]
Thank you very much, I'm waiting your update ❤️

**Comment by bofahad11** [comment]
Hey bro, is there any news about the problem

**Comment by RojanGamingYT** [comment]
The Issue could not be fixed from my side, still working on it and possibly maybe the discord API is blocking the request

**Comment by RojanGamingYT** [comment]
The New Version is **OUT** , This Issue has been Solved in that Version

**Comment by bofahad11** [comment]
Thanks, is it passing capatacha?

**Comment by RojanGamingYT** [comment]
it is, it now uses `selenium` & `chrome driver` so the captcha won't be a problem here

**Comment by bofahad11** [comment]
captcha will shown if you press submit, and username is really available

Try it

**Comment by RojanGamingYT** [comment]
I just tested it there isn't  a captcha when clicking submit and the code is working fine in my side

**Comment by bofahad11** [comment]
did you change the username, or it's not available?

**Comment by RojanGamingYT** [comment]
at line 86 `password_box.submit()` is commented , make sure you remove the # at the front to make it work

**Comment by RojanGamingYT** [comment]
I have removed the # and updated the code
